### PR TITLE
Add script to email contributing members about open votes

### PR DESCRIPTION
**Pull request by tbm**

### CODE REVIEW

**Comment by tbm** [comment]
I have done some testing and I believe this works as expected.  The idea would be to run the script from a cronjob once per day.

However, my database only contained one user and one vote, so it's possible I missed something major.

**Comment by tbm** [comment]
I pushed a new version:

1) This makes use of your new confguration mechanism.  That is indeed much cleaner.

2) I made it print out a message when it emails someone all the time (and not just when --dry-run is set). I think it's good to be aware when the script sends out emails, just in case something is wrong in the script and we're spamming people.

**Comment by tbm** [comment]
Feel free to make any changes you think make sense, or let me know and I can make a new version.

**Comment by u1f35c** [comment]
Minor change to use the configured SMTP_SERVER rather than localhost, and fix up a couple of PEP8 style issues, but merged.

**Comment by tbm** [comment]
> Minor change to use the configured SMTP_SERVER rather than localhost, and fix up a couple of PEP8 style issues

Oh yes, thanks for those!

**Pull request closed without merging**
